### ISSUE TITLE
create session error

### ISSUE THREAD

**Issue by DellaPreston** [BCAAFC/Gathering-Our-Voices#78]
enable button needed.
when I click  + Create Session 
i get : Internal Server Error

**Comment by Hoverbear** [comment]
Seems to be the problem:

```
Jan 05 11:45:24 gov-app node[6093]: ::ffff:127.0.0.1 - - [05/Jan/2017:19:45:24 +0000] "GET /account/workshop/34/session HTTP/1.0" 500 22
Jan 05 11:45:24 gov-app node[6093]: Error: Missing helper: "datetime"
Jan 05 11:45:24 gov-app node[6093]:     at Object.<anonymous> (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
Jan 05 11:45:24 gov-app node[6093]:     at Object.eval (eval at createFunctionContext (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:246)
Jan 05 11:45:24 gov-app node[6093]:     at main (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
Jan 05 11:45:24 gov-app node[6093]:     at ret (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
Jan 05 11:45:24 gov-app node[6093]:     at ret (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
Jan 05 11:45:24 gov-app node[6093]:     at Object.invokePartial (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
Jan 05 11:45:24 gov-app node[6093]:     at Object.invokePartialWrapper [as invokePartial] (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
Jan 05 11:45:24 gov-app node[6093]:     at Object.eval (eval at createFunctionContext (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
Jan 05 11:45:24 gov-app node[6093]:     at main (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
Jan 05 11:45:24 gov-app node[6093]:     at ret (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
Jan 05 11:45:24 gov-app node[6093]:     at ret (/home/app/gov/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
Jan 05 11:45:24 gov-app node[6093]:     at render_file (/home/app/gov/node_modules/hbs/lib/hbs.js:49:23)
Jan 05 11:45:24 gov-app node[6093]:     at render_with_layout (/home/app/gov/node_modules/hbs/lib/hbs.js:80:5)
Jan 05 11:45:24 gov-app node[6093]:     at Instance.middleware (/home/app/gov/node_modules/hbs/lib/hbs.js:140:12)
Jan 05 11:45:24 gov-app node[6093]:     at View.render (/home/app/gov/node_modules/express/lib/view.js:126:8)
Jan 05 11:45:24 gov-app node[6093]:     at tryRender (/home/app/gov/node_modules/express/lib/application.js:639:10)
```

**Comment by Hoverbear** [comment]
Please reopen if not fixed. Should be corrected.
